name: Modified Cross Repo
on: push
env:
  TARGET_REPO: create-pr-action
jobs:
  checkout:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4 #スクリプト実行にはチェックアウトが必要
      - run: chmod +x .github/scripts/token.sh 
      - id: create
        run: .github/scripts/token.sh #GitHub Appsトークン生成スクリプトの実行
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ env.TARGET_REPO }}
          path: ${{ env.TARGET_REPO }}
          token: ${{ steps.create.outputs.token }}
      - run: cat "${TARGET_REPO}/README.md"