name: Release
on:
  - push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    runs-on: ubuntu-24.04
    env:
      VERSION: ${{ github.ref_name }} #tag名やブランチ名
      permissions:
        contents: write #リリースノートの作成に必要なパーミッション
      steps:
        - uses: actions/checkout@v5
        - uses: actions/setup-go@v6
          with:
            go-version: 'v1.22'
        - run: |
            go build -ldflags "-X main.version=${VERSION}" \
            -o "${RUNNER_TEMP}/example" go/example/main.go
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}